Force of infection
ScottishCovidResponse/Simulation.jl pull request #26
Opened 2020-05-07 12:32 UTC by claireh93

I think this is ready to go but could do with a look over, particularly from @richardreeve to check the epi side of things.

2020-05-07 12:34 UTC, claireh93 commented on src/Epidemiology/EpiGenerate.jl
> +                births = rand(rng, Poisson(birthprob))
One thing in particular I changed was to have new virus drawn from a Poisson instead of Binomial because this made more sense to me. Do we think this is appropriate?

2020-05-08 09:51 UTC, jwscook commented on src/Epidemiology/EpiGenerate.jl
> +                births = rand(rng, Poisson(birthprob))
Is this still in need of confirmation @richardreeve @claireh93 ?

2020-05-08 09:53 UTC, claireh93 commented on src/Epidemiology/EpiGenerate.jl
> +                births = rand(rng, Poisson(birthprob))
Yes, but hoping to have a chat about it at some point today

2020-05-08 11:02 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +                births = rand(rng, Poisson(birthprob))
Yes, that seems sensible to me for now. Given that it's measuring force of infection, there's actually no reason for it to be Poisson either, because the force could be real-valued, and now we're going to separate out virus data from human data we can revisit this, but for now go ahead. However, shouldn't it be:
```julia
Poisson(epi.abundances.matrix[1, i] * birthprob)
```

2020-05-08 11:04 UTC, claireh93 commented on src/Epidemiology/EpiGenerate.jl
> +                births = rand(rng, Poisson(birthprob))
Cool okay sounds good. Well I was thinking that it makes more sense for virus to be drawn from the population size of infected categories (already factored into birthprob) than the amount of virus already there?

2020-05-08 11:27 UTC, richardreeve requested changes
I think most of this is fine, but there are a couple of things I'd like to resolve - particularly the units issue.

2020-05-08 11:27 UTC, richardreeve commented on docs/Structure.md
> +* Virus grows as the sum of several Binomal draws from each infection category, $NV_{k, c}$ ~ $Poisson(p_c)$ where $NV$ is new virus, $k$ is the current grid square, $c$ is the disease class, and $p_
If I was right about the Poisson(n*p), then it should change here too.

2020-05-08 11:27 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +    death_boost = traitmatch^-1
I'm not confident I know why this has changed, but I haven't had any time recently to look at the code, so I'm sure you're right. Hopefully in the next week or so my other responsibilities will ease off a bit and I'll be able to help more with the Julia model. Don't let me stop you merging though.

2020-05-08 11:27 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +    gs /= unit(gs)
I'm not confident this is a good idea - you're just stripping of the units without caring whether they are in m or km... then I think the model will give unexpected results if you switch like that. Maybe you can set a default grid scale with:
```julia
const GRIDSCALE = 1.0km
```
at the top level, and then use it here? Or probably better have the correct one of these parameters be unitful so they cancel. For the time being if you just want to merge this, can you make a const inside the package, so `Simulation.GRDISCALE` is always defined?

2020-05-08 11:27 UTC, richardreeve commented on src/Epidemiology/EpiParams.jl
> +      beta_force::TimeUnitType{U}
In fact force of infection may be *per unit area*.

2020-05-08 11:27 UTC, richardreeve commented on src/Epidemiology/EpiParams.jl
> +      beta_force::TimeUnitType{U}
More points where this could happen below...

2020-05-08 11:27 UTC, richardreeve commented on src/Epidemiology/EpiParams.jl
> +      beta_force::TimeUnitType{U}
e.g. here.

2020-05-08 11:27 UTC, richardreeve commented on src/Epidemiology/EpiParams.jl
> +      beta_force::TimeUnitType{U}
Actually, maybe I've got this the wrong way round. Maybe `beta_force` and `beta_env` are `force * area`, then you divide by area to get the force on an individual? We should have a chat about this when you're free to get my head around it...

2020-05-08 11:27 UTC, richardreeve commented on src/Epidemiology/EpiParams.jl
> +    ordered_transitions = [params.mu_1, params.mu_2, params.hospitalisation, params.sigma_1, params.sigma_2, params.sigma_hospital, params.death_home,
Could you use a named tuple here so that we know what each is? I'm not completely sure tbh.

2020-05-08 11:28 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +                births = rand(rng, Poisson(birthprob))
I'm probably misunderstanding then. Shall we have a quick chat about this?

2020-05-08 11:54 UTC, claireh93 commented on src/Epidemiology/EpiGenerate.jl
> +    death_boost = traitmatch^-1
Ah well, in the tests for running at different grid sizes the answers didn't match up because of this - i.e. 1 -> 4 -> 16 grid cells with the same initial amount of virus yielded different results. This was in there originally as a suggestion from Glenn, but I'm not sure it makes sense to have death rate being increased when there is a greater amount of existing virus anyhow.

2020-05-08 11:57 UTC, claireh93 commented on src/Epidemiology/EpiGenerate.jl
> +    gs /= unit(gs)
Oh yeah, good catch! I put this in as a bit of a hack originally and forgot it was there... I'll change now - I'll put it in as a const for now and then we can discuss the points you made below about beta_force

2020-05-08 12:36 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +    gs /= unit(gs)
Okay, should be divided by N (local population size).

2020-05-08 12:36 UTC, richardreeve commented on src/Epidemiology/EpiParams.jl
> +      beta_force::TimeUnitType{U}
Okay, can ignore all this.

2020-05-08 12:37 UTC, richardreeve commented on docs/Structure.md
> +* Virus grows as the sum of several Binomal draws from each infection category, $NV_{k, c}$ ~ $Poisson(p_c)$ where $NV$ is new virus, $k$ is the current grid square, $c$ is the disease class, and $p_
Okay - this should not be p_c (not a *p*).

2020-05-08 12:37 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +                births = rand(rng, Poisson(birthprob))
Okay, need to change birthprob and deathprob to different words as they are not probs.

2020-05-08 12:41 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +    death_boost = traitmatch^-1
Okay - delete birthboost, deathboost is fine.

2020-05-08 12:43 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +    gs /= unit(gs)
No need for a gridscale.

2020-05-08 15:01 UTC, claireh93 commented
I don't know why this is failing on the travis pr but not on the push - is this similar to the problem you had the other day @jwscook? All tests pass on my machine

2020-05-08 15:16 UTC, claireh93 commented
Okay I should have fixed the prob with the travis pr and addressed the other comments, so it should be good to merge once the checks have passed

2020-05-08 15:45 UTC, richardreeve requested changes
Looks good. Tiny edits then it's good to go.

2020-05-08 15:45 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +        N = sum(epi.abundances.matrix[susclass:end, i])
Sadly, this will allocate... need a loop.

2020-05-08 15:45 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +                #newbirthprob = 1.0 - exp(-birthprob)
Delete this line.

2020-05-08 15:57 UTC, claireh93 commented on src/Epidemiology/EpiGenerate.jl
> +        N = sum(epi.abundances.matrix[susclass:end, i])
I'm not sure I know what you mean?

2020-05-08 16:14 UTC, claireh93 commented on src/Epidemiology/EpiGenerate.jl
> +        N = sum(epi.abundances.matrix[susclass:end, i])
Okay actually I think I've got it

2020-05-08 16:22 UTC, richardreeve approved these changes

2020-05-08 19:32 UTC, merged