Ar/issue 148 b
ScottishCovidResponse/Simulation.jl pull request #37
Opened 2020-05-20 10:01 UTC by AlexRobson

WIP: for issue 148: https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/148

* Creates a separate virus and human abundancy matrix
* Creates accessor functions (`virus`) and `human`

* WIP: as does not handle changes to EpiList!

2020-05-20 10:17 UTC, AlexRobson commented on src/Epidemiology/EpiGenerate.jl
> +                trans = rand.(fill(rng, length(trans_prob)), Binomial.(human(epi.abundances)[:, i],  trans_prob))
line needs checking

2020-05-20 10:17 UTC, AlexRobson commented on src/Epidemiology/EpiGenerate.jl
> +  full_abun = human(epi.abundances)[sp, i]
line needs checking

2020-05-20 10:18 UTC, AlexRobson commented on test/canonical/test_SEI2HRD.jl
> +initial_pops = (
did this because added virus as accessor function so caused conflic

2020-05-20 10:18 UTC, AlexRobson commented on test/canonical/test_SEI2HRD.jl
> +human(epi.abundances)[4:5, 1] .= new_symptomatic
indexing changed briefly from 4:5 and 3:4 but didn't break test.

2020-05-20 14:36 UTC, claireh93 commented on src/Epidemiology/EpiGenerate.jl
> +                trans = rand.(fill(rng, length(trans_prob)), Binomial.(human(epi.abundances)[:, i],  trans_prob))
Okay, as discussed this should be fine to go as is, once age changes have been incorporated.

2020-05-20 14:38 UTC, claireh93 commented on src/Epidemiology/EpiGenerate.jl
> +  full_abun = human(epi.abundances)[sp, i]
I feel like this should be okay too, but might need checking against the rebased age changes

2020-05-20 14:39 UTC, claireh93 commented on test/canonical/test_SEI2HRD.jl
> +human(epi.abundances)[4:5, 1] .= new_symptomatic
We believe this is because the index only shifted by 1 category, so at least one of the infectious categories is still being filled with infectious individuals.

2020-05-24 12:09 UTC, AlexRobson commented on test/canonical/test_SEIRS.jl
> +@test_broken all(diff(vec(sum(abuns[idx_sus, :, :], dims = 1))) .<= 0)
line needs checking

2020-05-24 12:09 UTC, AlexRobson commented on test/canonical/test_SEIRS.jl
> +@test_broken all(diff(vec(sum(abuns[idx_rec, :, :], dims = 1))) .>= 0)
line needs checking

2020-05-24 12:11 UTC, AlexRobson commented
@claireh93 I've merged in the latest dev on this. So this should be ready. I've added in some extra tests as discussed to handle the upcoming index shift. However, there are a couple of tests that I'd like a quick look at (they are marked as "@test_broken"), i've also commented them.

2020-05-25 11:03 UTC, claireh93 commented on test/canonical/test_SEIRS.jl
> +@test_broken all(diff(vec(sum(abuns[idx_sus, :, :], dims = 1))) .<= 0)
The only thing we might need to think about here is a situation in which birth or influx of recovered class with waning immunity (R -> S) might overtake infection. However, the way it's parameterised currently means this shouldn't happen (do these tests currently pass?) so I think this should be fine!

2020-05-25 11:04 UTC, claireh93 commented on test/canonical/test_SEIRS.jl
> +@test_broken all(diff(vec(sum(abuns[idx_rec, :, :], dims = 1))) .>= 0)
Same here - there might be some cases in which waning immunity is strong enough that the recovered class could decrease (moving to S). But I don't think this is the case for this parameter set.

2020-05-25 12:13 UTC, AlexRobson commented on test/canonical/test_SEI2HRD.jl
> +@test all(diff(vec(sum(abuns[idx_sus, :, :], dims = 1))) .<= 0)
.

2020-05-25 12:15 UTC, AlexRobson commented on test/canonical/test_SEIRS.jl
> +@test_broken all(diff(vec(sum(abuns[idx_sus, :, :], dims = 1))) .<= 0)
Thanks for the comment. So just to clarify, this test will break if I change `test_broken` -> `test`, and my understanding from the above is that this isn't expected, and that this test should pass, contrrary to the test outcome.  I re-read my earlier comment and I should have said explicitely that these tests marked `test_broken` are failing tests, i.e. if i change `test_broken` -> `test` CI will fail for these ones. 

Just to add more commentary around this, I set these up with some presumptions around what the model was doing with birth/death = 0 that overtime all the population will move from susceptible to either the recovered state or the death state. Now these tests work in the two other experiments, but fail here. So I wanted to clarify whether this test is expected to pass or not in this experimental set up. 

On reflection, it may not be a good test for me to add given scenarios like you described can happen (with R -> S), but as commented it is passing in a couple of the other files, so I wnted to clarify, e.g. here: https://github.com/ScottishCovidResponse/Simulation.jl/pull/37/files#diff-66c0c10bac46ffa1d30f3f821a40aeddR180 [I added a comment to the line in question].

2020-05-25 14:44 UTC, claireh93 commented on test/canonical/test_SEIRS.jl
> +@test_broken all(diff(vec(sum(abuns[idx_sus, :, :], dims = 1))) .<= 0)
Ahh I see, thanks @AlexRobson! I have just run the test again on SEIRS to check the behaviour and found there is some flux in the S category from this waning immunity (R -> S) which on balance, we would be expecting. The other model types won't suffer from this problem (apart from maybe SIS), because none of them have movement between these two categories - final destination tends to be either R or D categories. So perhaps we just take out this test for SEIRS?

2020-05-25 16:23 UTC, richardreeve requested changes
A few minor fixes. I think the issue of indexing needs to be more generally resolved, as I'm confused by it to be honest (i.e. not in this PR).

2020-05-25 16:23 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +                trans = rand.(fill(rng, length(trans_prob)), Binomial.(human(epi.abundances)[:, i],  trans_prob))
I don't think this is legal. You're copying the same rng seed repeatedly here. This is obviously a problem with the original code, but should be fixed here anyway. Just iterate over the vector of binomials.

2020-05-25 16:23 UTC, richardreeve commented on src/Epidemiology/EpiLandscape.jl
> +  function EpiLandscape(abun1::Matrix{Int64}, abun2::Matrix{Int64}, d1::Tuple)
Can we call these `human_abun` and `virus_abun` just for clarity?

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SEI2HRD.jl
> +initial_pops = (
I think this is a big improvement actually, but should be passed through as a NamedTuple to make sure the names are preserved. Then you can use them at the other end to make sure the names are in the right order.

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SEI2HRD.jl
> +abun = [initial_pops...]
So you can delete this.

2020-05-25 16:23 UTC, richardreeve commented on src/Epidemiology/EpiLandscape.jl
> +
You can delete these lines

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SEI2HRD.jl
> +human(epi.abundances)[4:5, 1] .= new_symptomatic
i.e.think we need to resolve this later - this indexing issue is a problem, but we need to resolve it more generally. In fact I think we are talking about using AxisArrays or something elsewhere, and maybe should here?

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SEI2HRD.jl
> +@test sum(abuns[end, :, 365]) == (initial_pops[:susceptible] + new_symptomatic + new_asymptomatic)
I know this is just a stylistic issue, but how about `initial_pops.susceptible`?

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SEI2HRD.jl
> +abun = [initial_pops...]
Again can we switch to using `NamedTuple` throughout?

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SEI2HRD.jl
> +@test sum(abuns[2, :, 365]) == initial_pops[:susceptible]
And `initial_pops.susceptible` again...

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SEIR.jl
> +abun = [initial_pops...]
Ditto for SEIR

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SEIR.jl
> +@test all(sum(abuns[2:5, :, :], dims = (1, 2)) .== (initial_pops[:susceptible] + initial_pops[:infected]))
Ditto

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SEIRS.jl
> +abun = [initial_pops...]
Ditto for SEIRS

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SEIRS.jl
> +@test all(sum(abuns[2:5, :, :], dims = (1, 2)) .== (initial_pops[:susceptible] + initial_pops[:infected]))
Ditto

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SIR.jl
> +    abun = [initial_pops...]
Ditto for SIR

2020-05-25 16:23 UTC, richardreeve commented on test/canonical/test_SIR.jl
> +        (initial_pops[:susceptible] + initial_pops[:infected] + initial_pops[:recovered]))
Ditto

2020-05-26 08:37 UTC, AlexRobson commented on src/Epidemiology/EpiGenerate.jl
> +                trans = rand.(fill(rng, length(trans_prob)), Binomial.(human(epi.abundances)[:, i],  trans_prob))
resolved with `trans = collect(rand(rng, b) for b in Binomial.(human(epi.abundances)[susclass:end, i],  trans_prob))`

2020-05-26 08:43 UTC, AlexRobson commented on test/canonical/test_SEI2HRD.jl
> +initial_pops = (
Actually namedtuples was what i thought on resolving the issue around indexing. However, that's best put into a seperarate MR. It'll be tied up with introducing AxisArrays for the abundancy matrix (as essentially that's where these compartments are represented). I'm resolving this by creating this issue: https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/281. Was always the intension to follow up this MR with a subsequent one to handle the indexing issues.

2020-05-26 08:43 UTC, AlexRobson commented on test/canonical/test_SEIRS.jl
> +@test_broken all(diff(vec(sum(abuns[idx_sus, :, :], dims = 1))) .<= 0)
Resolved by removing both of these tests.

2020-05-26 08:45 UTC, AlexRobson commented on test/canonical/test_SEI2HRD.jl
> +@test sum(abuns[end, :, 365]) == (initial_pops[:susceptible] + new_symptomatic + new_asymptomatic)
should have resolved this everywhere

2020-05-26 08:48 UTC, AlexRobson commented on test/canonical/test_SEI2HRD.jl
> +human(epi.abundances)[4:5, 1] .= new_symptomatic
https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/281

2020-05-26 08:54 UTC, AlexRobson commented on test/canonical/test_SEI2HRD.jl
> +abun = [initial_pops...]
I've put this into a seperate issue: https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/281

I made a comment somewhere on this but I can't see it on github...anyway, introducing namedtuples was an intended follow up MR.

2020-05-26 08:55 UTC, AlexRobson commented on test/canonical/test_SEI2HRD.jl
> +abun = [initial_pops...]
related to introduced named tuples.

2020-05-26 08:56 UTC, AlexRobson commented on src/Epidemiology/EpiGenerate.jl
> +                trans = collect(rand(rng, b) for b in Binomial.(human(epi.abundances)[susclass:end, i],  trans_prob))
this line is the resolution to the binomial vector comment. For some reason my comment there was lost and i can't unresolve it to add it again...

2020-05-26 08:58 UTC, AlexRobson commented
OK. I'll stop working on this i think that I've got all the comments resolved. Subsequent MRs can handle introducing NamedTuples and AxisArrays.

2020-05-26 09:26 UTC, claireh93 commented
Thanks @AlexRobson! Sorry I hadn't got round to telling @richardreeve our plan about spreading things out over multiple PRs, but I think this looks like a great first step. Are we ready to merge after CI is finished?

2020-05-26 12:56 UTC, AlexRobson commented
Yeah, it should be good to go now. CI is passing.

2020-05-26 13:29 UTC, claireh93 approved these changes
Looks good! I'm not sure if @richardreeve has to approve the changes directly though?

2020-05-26 14:22 UTC, claireh93 commented on src/Epidemiology/EpiGenerate.jl
> +                birthrate = params.virus_growth[j] * timestep * virus(epi.abundances)[j + 1, i]
Ah sorry, I just realised that there's a tiny mistake here - this should be human(epi.abundances) and not virus - virus being generated from infectious human populations.

2020-05-26 15:01 UTC, richardreeve commented
Claire has approved and can merge this - it doesn't require me. Obviously the conflicts need fixed first (and Claire's last comment).

2020-05-26 21:27 UTC, richardreeve requested changes
It's a tiny thing, but can you fix this function definition and then we can leave the rest for the new PR?

2020-05-26 21:27 UTC, richardreeve commented on src/Epidemiology/EpiLandscape.jl
> +  function EpiLandscape(abun1::Matrix{Int64}, abun2::Matrix{Int64}, d1::Tuple)
I'm okay with leaving everything else to the next PR, but can we just fix this so it's obvious what the two matrices are given you've just introduced them in this PR

2020-05-26 21:32 UTC, AlexRobson commented
> It's a tiny thing, but can you fix this function definition and then we can leave the rest for the new PR?

Sorted. Sorry, I'd only dealt with the line below...

2020-05-26 21:37 UTC, AlexRobson commented on src/Epidemiology/EpiGenerate.jl
> +                birthrate = params.virus_growth[j] * timestep * virus(epi.abundances)[j + 1, i]
Hm, no test seemed to react to this change.

2020-05-26 21:43 UTC, richardreeve approved these changes

2020-05-27 08:34 UTC, merged