WIP: Parse Scottish population data
ScottishCovidResponse/Simulation.jl pull request #41
Opened 2020-05-27 21:40 UTC by eperim

Closes https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/270

Still need tests.

2020-05-29 09:30 UTC, claireh93 commented
Hi @eperim, this looks good! The only thing I would say is that we are reading in the demographic data, summing it and then splitting it apart randomly over age categories again in lines 75-79. I think we need to work out a way to input the age-aggregated data into `simplehabitatAE`, but maybe that's worth adding as a new issue? I also think something might be erroring out during testing?

2020-05-29 10:35 UTC, eperim commented
Oh cool. I will take another look and make sure that the ages are preserved.

About the CI failure, the issue is lack of memory for the CI runners. It works fine locally (and for one of the CI runners), but it seems that the data is too big for some of them. An alternative could be creating a smaller dataset for the test to mitigate this. Or maybe @jwscook has a better idea?

2020-05-29 12:02 UTC, wytbella commented on examples/Epidemiology/Scotland_run.jl
> +total_pop = Matrix(sum(scotpop, dims=3)[:, :])
I _think_ you can have `total_pop` as an AxisArray Matrix now, preserving the grid x, y information

2020-05-30 19:17 UTC, eperim commented on examples/Epidemiology/Scotland_run.jl
> +total_pop = Matrix(sum(scotpop, dims=3)[:, :])
That works, indeed, I'll change that.

2020-05-30 20:11 UTC, eperim commented on examples/Epidemiology/Scotland_run.jl
> +scotpop = parse_scotpop(Simulation.path("test", "examples", "scrc_demographics.h5"), grid="1k")
I changed this to the 1k x 1k grid, instead of the 10k x 10k grid because https://github.com/ScottishCovidResponse/Simulation.jl/pull/41/files#diff-e8c26f5226daa3e1cdde61c294185a66R76 would break otherwise.

With the large grid, the Julia process simply gets killed, which might suggest it's trying to allocate too much stuff in memory. Not sure if this is expected or if it might be the symptom of something being inefficient, but it should be investigated separately from this PR.

2020-05-30 20:15 UTC, eperim commented on examples/Epidemiology/Scotland_run.jl
> +samp = sample(1:N_cells, weights(1.0 .* sum(epi.abundances.matrix, dims=1)), 100)
@claireh93 please double check the logic here, because I am computing the weights differently from before. I add up over all disease classes (only susceptible should be non-zero) and over all ages, in order to get the total population size of each cell.

Also, I think there might be an issue with this part, because in the part below we add individuals to `Exposed`, but never remove them from `Susceptible`, so we are effectively adding more individuals to the total population.

2020-05-30 20:19 UTC, eperim commented
Using this data, even if we adopt the 1k x 1k grid, there is no way this example will run in an average laptop, because of
```
abuns = zeros(Int64, size(epi.abundances.matrix, 1), N_cells, 366)
```
being a gigantic array, equivalent to a 48678 per 1million matrix. Should we be ok with this only running on the large clusters or should we coarsen it down?

2020-05-31 21:36 UTC, richardreeve commented
As @sdl1 says in SCRC-309, we can store records in an hdf5 file in slices as we go along, so we don't need to have the 366 deep array, we can just have the current state. We can also reduce the size of the integers we are using to UInt16 and still cover everywhere in the UK with a factor of 4 spare even with only 1 demographic group and everyone susceptible (Islington is approx 16k/sq km). We have a final problem that 75% of Scotland is sea, which is wasteful of space, despite the fact that the update step is pretty efficient at ignoring these inactive squares. All of those together would take us down to 1MB rather than 6GB for Scotland!

In the meanwhile running it at 10km should be fine - I'm not sure what you mean [here](https://github.com/ScottishCovidResponse/Simulation.jl/pull/41#discussion_r432882542) by it breaking?

2020-05-31 22:27 UTC, richardreeve commented on examples/Epidemiology/Scotland_run.jl
> +samp = sample(1:N_cells, weights(1.0 .* sum(epi.abundances.matrix, dims=1)), 100)
Shall we just add 100 exposed people in total (rather than the current 100 x 10) by doing 100 multinomial draws from the whole `epi.abundances.matrix` susceptibles? Then subtract them from from the susceptible column and add them to the exposed.

2020-05-31 22:39 UTC, richardreeve commented on examples/Epidemiology/Scotland_run.jl
> +scotpop = parse_scotpop(Simulation.path("test", "examples", "scrc_demographics.h5"), grid="1k")
I think this is a bug in `parse_scotpop()`. See comments there.

2020-05-31 22:58 UTC, richardreeve requested changes
Looks good, but there's a problem with the grid creation in `parse_scotpop()` and a couple of other small issues.

2020-05-31 22:58 UTC, richardreeve commented on src/Epidemiology/data_utils.jl
> +    grid_size = parse(Int, chop(grid)) * 1000
At the moment this is the wrong way round - should be `1000 ÷ parse(Int, chop(grid))`. But the maximum x and y axes should be `maximum(parse.(Int, getindex.(split.(data["grid1k_id"], repeat(["-"], length(data["grid1k_id"]))), 1)))` and `maximum(parse.(Int, getindex.(split.(data["grid1k_id"], repeat(["-"], length(data["grid1k_id"]))), 2)))`, though there's definitely a cleaner way of doing this! That way you can make the `grid_size` as tight as possible.

2020-05-31 22:58 UTC, richardreeve commented on src/Epidemiology/data_utils.jl
> +    parse_scotpop(path; grid="10k")
Can we make this `parse_hdf5()` and add a component argument?

2020-05-31 22:58 UTC, richardreeve commented on examples/Epidemiology/Scotland_run.jl
> +scotpop = parse_scotpop(Simulation.path("test", "examples", "scrc_demographics.h5"), grid="1k")
Can we also use `parse_hdf5()` and add `component="scotland_2018"` here please?

2020-05-31 22:58 UTC, richardreeve commented on src/Epidemiology/data_utils.jl
> +        grid_x=collect(1:grid_size),
If we're using `AxisArray`s, is there any reason not to add in the right grid size in km?

2020-05-31 22:58 UTC, richardreeve commented on src/Simulation.jl
> +export parse_scotpop
`parse_hdf5`

2020-05-31 22:58 UTC, richardreeve commented on test/test_data_utils.jl
> +    scotpop_10k = parse_scotpop(path)
`component="scotland_2018"`

2020-05-31 22:58 UTC, richardreeve commented on test/test_data_utils.jl
> +    scotpop_1k = parse_scotpop(path, grid="1k")
ditto

2020-05-31 22:58 UTC, richardreeve commented on test/test_data_utils.jl
> +    @test size(scotpop_1k) == (1000, 1000, 19)
fix

2020-05-31 22:58 UTC, richardreeve commented on test/test_data_utils.jl
> +    @test_throws ArgumentError parse_scotpop(path, grid="5k")
fix

2020-06-01 18:13 UTC, eperim commented on examples/Epidemiology/Scotland_run.jl
> +samp = sample(1:N_cells, weights(1.0 .* sum(epi.abundances.matrix, dims=1)), 100)
The susceptible is not a column, though, but a matrix. From which age to we subtract from/add to?

2020-06-01 18:18 UTC, eperim commented on src/Epidemiology/data_utils.jl
> +    grid_size = parse(Int, chop(grid)) * 1000
Not sure I get the reasoning here. We have the option of a 1,000 by 1,000 grid or of a 10,000 by 10,000 grid, isn't it? That is what `grid_size` is getting. `1000 ÷ parse(Int, chop(grid))` will be either 1,000 or 100.

Are you suggesting to not include in the matrix cells that have zero count?

2020-06-01 18:20 UTC, eperim commented on src/Epidemiology/data_utils.jl
> +        grid_x=collect(1:grid_size),
I am not sure I have that information.

2020-06-01 18:20 UTC, eperim commented on test/test_data_utils.jl
> +    @test size(scotpop_1k) == (1000, 1000, 19)
Sorry, but fix what?

2020-06-01 18:21 UTC, eperim commented on test/test_data_utils.jl
> +    @test_throws ArgumentError parse_scotpop(path, grid="5k")
Sorry, but fix what?

2020-06-01 18:25 UTC, eperim commented
> I'm not sure what you mean [here](https://github.com/ScottishCovidResponse/Simulation.jl/pull/41#discussion_r432882542) by it breaking?

The Julia process gets killed, without a stack trace. That usually happens when allocating something too large in memory. e.g:
```julia
julia> A = zeros(1000000, 1000000)
[1]    6691 killed     /Applications/Julia-1.4.app/Contents/Resources/julia/bin/julia --project=@.
```

2020-06-02 10:02 UTC, richardreeve commented on test/test_data_utils.jl
> +    @test_throws ArgumentError parse_scotpop(path, grid="5k")
Sorry - parse_scotpop is now parse_hdf5.

2020-06-02 10:02 UTC, richardreeve commented on test/test_data_utils.jl
> +    @test size(scotpop_1k) == (1000, 1000, 19)
Sorry - the sizes will now be wrong won't they?

2020-06-02 10:04 UTC, richardreeve commented on src/Epidemiology/data_utils.jl
> +        grid_x=collect(1:grid_size),
That's the "1k" or "10k" isn't it?

2020-06-02 10:06 UTC, richardreeve commented on src/Epidemiology/data_utils.jl
> +        grid_x=collect(1:grid_size),
Ah, I suddenly think that you misunderstood what 1k and 10k referred to! It's the size of a grid square in km. It should probably be renamed to make that more explicit if I've now realised what's going on?

2020-06-02 10:18 UTC, richardreeve commented on examples/Epidemiology/Scotland_run.jl
> +samp = sample(1:N_cells, weights(1.0 .* sum(epi.abundances.matrix, dims=1)), 100)
We just draw from the whole human abundances matrix, weighted by abundance in that matrix. Since everyone is susceptible, that'll draw from all of the susceptible populations in all age classes. Then we just move those individuals from susceptible to exposed.

2020-06-02 10:20 UTC, richardreeve commented on src/Epidemiology/data_utils.jl
> +    grid_size = parse(Int, chop(grid)) * 1000
Ah, I have suddenly realised that you misunderstood what 1k and 10k referred to! It's the size of a grid square in km. It should probably be renamed to 1km and 10km to make that more explicit if I've now realised what's going on? And then I'm proposing only using the grid size that the file actually uses.

2020-06-02 10:22 UTC, richardreeve commented
Right - I think I understand now. All of this is a confusion about what 1k means. We'll fix the component name in a future version of the file!

2020-06-07 16:43 UTC, richardreeve approved these changes

2020-06-07 16:43 UTC, merged