Fix bug in how the initial infecteds are populated.
ScottishCovidResponse/Simulation.jl pull request #50
Opened 2020-06-11 11:13 UTC by claireh93

Closes ScottishCovidResponse/SCRCIssueTracking#424

Found problem with negative abundances that appeared every so often - isolated problem instead to EpiSystem set up, where the indexing on adding exposed/removing susceptible individuals was wrong.

2020-06-11 22:44 UTC, richardreeve requested changes
Minor fix?

2020-06-11 22:44 UTC, richardreeve commented on examples/Epidemiology/Scotland_run.jl
> +    epi.abundances.matrix[vcat(cat_idx[age_ids[i], 2]...), cell_ids[i]] .= 1
Can't we get rid of the `vcat(...)`? Isn't it just `cat_idx[age_ids[i], 2]`? Also, presumably you should check that `epi.abundances.matrix[cat_idx[age_ids[i], 1], cell_ids[i]] > 0` before you do this in case you've selected a 1 twice?

2020-06-11 22:44 UTC, richardreeve commented on examples/Epidemiology/Scotland_run.jl
> +        epi.abundances.matrix[vcat(cat_idx[age_ids[i], 1]...), cell_ids[i]] .- 1
Is this just `epi.abundances.matrix[cat_idx[age_ids[i], 1], cell_ids[i]] .-= 1`

2020-06-12 12:08 UTC, claireh93 commented
@richardreeve okay those suggestions should be resolved now!

2020-06-14 22:22 UTC, richardreeve approved these changes

2020-06-14 22:22 UTC, merged