WIP: issue 426
ScottishCovidResponse/Simulation.jl pull request #51
Opened 2020-06-11 17:47 UTC by claireh93

Changed virus loop to be calculated deterministically and randomised at end, along with other speed ups to `virusmove!`, which runs very slowly with multiple age classes.

`Scotland_run.jl` should now take ~12 mins to run 1 year on a 30 core machine, rather than 3.5hrs previously! Still more to do - have identified allocations in `traitfun` and type instability in `epienv`.

2020-06-15 13:55 UTC, richardreeve commented
@eperim Given you are now running (or trying to run!) the model on DiRAC, it may be worth using this branch, as it runs at more like the speed we would expect (though I'm confident there are still a lot of speed improvements to go).

2020-06-15 13:58 UTC, richardreeve commented
@claireh93 Happy to chat about this if you'd like - this is starting to run much more like the speed we expected now. One thing in particular though now it's running at a more sensible speed - what speed-up do you see for the multi-threaded code? Single threaded should be 2h given what you're saying above about 30 cores. If it's not linear, we should start targetting it before we move to the MPI code.

2020-06-18 14:38 UTC, claireh93 commented
Closes ScottishCovidResponse/SCRCIssueTracking#426 and also closes ScottishCovidResponse/SCRCIssueTracking#408

Summary of main changes to the code:

- Movement is now calculated deterministically and randomised at the end through a Poisson draw.

- We can now choose any type of integer for the `EpiLandscape` - in `Scotland_run` this is now UInt16.

- Wrap examples into functions.

- Fixed type instabilities and other memory allocations.

- Run `Scotland_run` on a 1km grid now with slightly smaller dispersal kernels.

2020-06-22 00:08 UTC, richardreeve requested changes
There is a small type instability still in `sum_pop` and a couple of other things, but looks good.

2020-06-22 00:08 UTC, richardreeve commented on src/Epidemiology/EpiSystem.jl
> +    rel::AbstractTraitRelationship, IntType::U) where {F<:Function, U <: Integer}
You talk about `IntType` a lot here, but it isn't a type - it's just a number... shouldn't this have a different name (and be lower case)?

2020-06-22 00:08 UTC, richardreeve commented on src/Epidemiology/EpiHelper.jl
> +            datatype(typeof(abuns[1])),
`eltype(abuns)`

2020-06-22 00:08 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +function sum_pop(M::Matrix{U}, i::Int64) where U <: Integer
```julia
function sum_pop(M::Matrix{R}, i::Int64) where R <: Real
n = zero(R)
```
then you only need one function... or are you doing this to make sure you have a `Int64` or a `Float64`?

2020-06-22 00:08 UTC, richardreeve commented on src/Epidemiology/EpiGenerate.jl
> +function sum_pop(V::Vector{Float64})
Same here - particularly because `N` is type unstable here:
```julia
function sum_pop(M::vector{R}) where R <: Real
n = zero(R)
```

2020-06-22 00:08 UTC, richardreeve commented on src/Epidemiology/EpiLandscape.jl
> +function emptyepilandscape(epienv::GridEpiEnv, epilist::EpiList, IntType::U) where U <: Integer
again, this should be lower case or an actual type...

2020-06-22 09:18 UTC, claireh93 commented on src/Epidemiology/EpiGenerate.jl
> +function sum_pop(M::Matrix{U}, i::Int64) where U <: Integer
No that makes more sense - I shall change it

2020-06-22 09:22 UTC, claireh93 commented
Okay great thanks, I have hopefully fixed those in the latest commit

2020-06-22 18:24 UTC, richardreeve approved these changes

2020-06-22 18:58 UTC, merged