Add minimal instructions for running on Dirac
ScottishCovidResponse/Simulation.jl pull request #64
Opened 2020-07-07 21:13 UTC by eperim

These instructions should be enough for running experiments using multithreading. They are very likely not the best way to do so, but it should work.

2020-07-08 00:13 UTC, richardreeve requested changes
Doesn't quite work for me. I suspect that a few iterations built up enough stuff in your .julia folder that it seemed to have been resolved.

2020-07-08 00:13 UTC, richardreeve commented on docs/src/HPC.md
> +Pkg.add(PackageSpec(url="https://github.com/ScottishCovidResponse/Simulation.jl.git"))
This doesn't work as a command inside a job unless Simulation has already been added on the head node - it just fails to build. Also, it would be easier to have a separate file with this in which runs separately to instantiate the project in the folder we're in, followed by running the desired executable file.

2020-07-08 00:13 UTC, richardreeve commented on docs/src/HPC.md
> +name = "RAMP"
It would be convenient to have all of the necessary files downloadable from the repo.

2020-07-08 00:13 UTC, richardreeve commented on docs/src/HPC.md
> +stdbuf -oL -eL julia --project=@. $inputbasename
Add in the running the setup script...

2020-07-14 17:27 UTC, eperim commented on docs/src/HPC.md
> +name = "RAMP"
This files are experiment-specific, though (as each may require different packages, depending on something they do). Do you want to have the one that runs with Scotland_run added?

2020-07-14 21:09 UTC, eperim commented on docs/src/HPC.md
> +Pkg.add(PackageSpec(url="https://github.com/ScottishCovidResponse/Simulation.jl.git"))
I updated the files and the instructions, please let me know if they work for you now. It's a bit weird, because I double checked and my base environment is completely empty, and everything runs on a single node. Hopefully it won't break for you again.

2020-07-14 21:09 UTC, eperim commented on docs/src/HPC.md
> +name = "RAMP"
Added stuff to Examples/Epidemiology/HPC

2020-07-16 21:48 UTC, richardreeve approved these changes

2020-07-16 21:49 UTC, richardreeve approved these changes

2020-07-16 21:49 UTC, merged