Jc/deterministic: Enable Simulation.jl to run as a deterministic code rather than stochastic
ScottishCovidResponse/Simulation.jl pull request #68
Opened 2020-07-15 10:03 UTC by jwscook

This PR shows how the behaviour of `rand` and `rand!` can be altered via multiple dispatch on a custom `Random.AbstractRNG` type so that `Simulation.jl` can behave deterministically i.e.:

```julia
rand(::CustomRNG, dist::Distributions.Binomial) = median(dist)
```

This is proof of principle that the whole code can be made to execute a deterministic version of the model, including invariance to the number of threads, at no extra computational cost. 

Importantly the "stochastic" parts of the code can be deployed in this manner to enable deterministic testing. The barrier to full and proper unit testing is subsequently lowered.

2020-07-15 10:04 UTC, jwscook commented on examples/Epidemiology/SEI3HRD_example.jl
> +const stochasticmode = true
flat to call `rand` and `rand!` with a the default `MersenneTwister` random number generator or a custom one that `<: Random.AbstractRNG` (in this case MedianGenerator) and has dispatch method defined below.

2020-07-15 10:05 UTC, jwscook commented on examples/Epidemiology/SEI3HRD_example.jl
> +const seed = hash(time()) # seed used for Random.jl and therefore rngs used in Simulation.jl
I wanted to be sure that if normal calls to `rand` or `rand!` were being made then I would get different answers every time

2020-07-15 10:05 UTC, jwscook commented on examples/Epidemiology/SEI3HRD_example.jl
> +const ic_rng = Random.MersenneTwister(0) # rng for initial conditions in this file
This is used only in this file and doesn't propagate into the rest of the code bases. It's used to ensure I have the same initial conditions each time.

2020-07-15 10:06 UTC, jwscook commented on examples/Epidemiology/SEI3HRD_example.jl
> +struct MedianGenerator <: Random.AbstractRNG end
This concrete `AbstractRNG` struct allows me to alter the dispatch of calls to `rand` and `rand!` in `Simulation.jl/src` without changing the code there except as shown in the diff of this PR.

2020-07-15 10:07 UTC, jwscook commented on examples/Epidemiology/SEI3HRD_example.jl
> +rand(::MedianGenerator, dist::Distribution{Univariate,S}) where {S<:ValueSupport} = median(dist)
Define these methods to dispatch `rand` and `rand!` on `MedianGenerator`

2020-07-15 10:07 UTC, jwscook commented on examples/Epidemiology/SEI3HRD_example.jl
> +median(dist::Distribution{Multivariate,S}) where {S<:ValueSupport} = dist.n .* dist.p
`median(::Distribution{Multivariate,S}) where {S<:ValueSupport}` isn't defined in `Distributions` so I made something up. This may well be wrong!

2020-07-15 10:09 UTC, jwscook commented on examples/Epidemiology/SEI3HRD_example.jl
> +    epi = EpiSystem(epilist, epienv, rel, scotpop; rngtype=rngtype)
`EpiSystem` now takes a `rngtype` kwarg so that `EpiLandscape` can have a vector of `MersenneTwisters` by default, or a vector of  `MedianGenerator`s!

2020-07-15 10:09 UTC, jwscook commented on src/Epidemiology/EpiGenerate.jl
> +        rand!(ml.rngs[1], Multinomial(epilist.human.abun[i], len), (@view ml.matrix[i, :]))
This guy and the one below needed to have the custom RNG passed into to it to fully alter all calss to `rand!`

2020-07-15 11:50 UTC, jwscook commented on src/Epidemiology/EpiGenerate.jl
> +        rand!(ml.rngs[1], Multinomial(epilist.virus.abun[i], len), (@view ml.matrix_v[i, :]))
had to change this guy too so that `rand!` gets called with the custom configured RNG

2020-07-23 13:29 UTC, richardreeve submitted a review, later dismissed
I'm completely happy with this now, but I see it has moved back to WIP - is that just for my benefit? If so, then please just merge.

2020-07-23 16:13 UTC, jwscook commented
I was going to put the `MedianGenerator` into `src` and then add another constructor to the `EpiSystem` (landscape? env?) with an enum argument that selects the MersenneTwister with `:stochastic` and the MedianGenerator with `:deterministic`. The other constructor that takes a `Random.AbstractRNG` will stick around.

2020-07-23 20:09 UTC, richardreeve commented
Ah, yes - putting MedianGenerator in more generally would be great.

2020-07-28 16:02 UTC, jwscook commented
@richardreeve Are you sure about your implementation of `median` for `Multinomial`s? The test in `test/test_MedianGenerator` show what the outputs are, and they look strange to me. I think there is a separate issue too, which is causing other failures.

2020-07-28 17:00 UTC, jwscook commented
It seems to me that the pattern that `median(::Multivariate)` should be producing is (based purely off looking at the current implementation and then guessing):

```julia
function median(dist::Multinomial)
  m = length(dist.p)
  v = Int64(floor(dist.n / m)); output = zeros(Int64, m) .+ v
  output[m:-1:m-mod(dist.n, m)+1] .+= 1
  return  output
end
```

```julia
julia> for j in 1:3, i in 0:3*j; println(i," ", j, " ", median(Multinomial(i, j))'); end
0 1 [0]
1 1 [1]
2 1 [2]
3 1 [3]
0 2 [0 0]
1 2 [0 1]
2 2 [1 1]
3 2 [1 2]
4 2 [2 2]
5 2 [2 3]
6 2 [3 3]
0 3 [0 0 0]
1 3 [0 0 1]
2 3 [0 1 1]
3 3 [1 1 1]
4 3 [1 1 2]
5 3 [1 2 2]
6 3 [2 2 2]
7 3 [2 2 3]
8 3 [2 3 3]
9 3 [3 3 3]
```

The current implementation does this


```julia
julia> for j in 1:3, i in 0:3*j; try println(i," ", j, " ", median(Multinomial(i, j))') catch; println(i, " ",j); end;end
0 1 [0]
1 1 [1]
2 1 [2]
3 1 [3]
0 2 [0 0]
1 2
2 2 [1 1]
3 2 [1 2]
4 2 [2 2]
5 2
6 2 [3 3]
0 3 [0 0 0]
1 3 [1 1 1]
2 3 [0 1 1]
3 3 [1 1 1]
4 3 [2 2 2]
5 3 [1 2 2]
6 3 [2 2 2]
7 3 [3 3 3]
8 3 [2 3 3]
9 3 [3 3 3]
```

2020-07-29 12:24 UTC, jwscook commented on test/test_MedianGenerator.jl
> +    @testset "issorted" begin
Should it be sorted? @richardreeve  suggests not

2020-07-30 15:09 UTC, richardreeve commented
Sorry - I don't know what I was up to - I tested it on a few ad hoc examples but clearly nonsense - yours is much better. Please do go ahead with your solution.

2020-07-30 15:57 UTC, richardreeve commented on test/test_MedianGenerator.jl
> +    @testset "issorted" begin
I understand what you mean now. If you're making all of the `p` values equal, then yes, it should be sorted I guess - easiest way of making sure it's deterministic. I was imagining the general case where you are putting in a `p` vector instead of a `k` which counts the number of equally likely compartments, in which case there is no guarantee.

2020-07-30 16:40 UTC, jwscook commented
I'm 100% not surprised what I wrote was wrong - it's a complete stab in the dark.

2020-08-12 12:35 UTC, jwscook commented
- Median has to be plausible as a deterministic result.
- Mode would also be suitable
- All values should be between the mean and mean-1.
- The total should be  ...

2020-08-12 12:39 UTC, jwscook commented
It needs to work for `Multinomial(number of trials, length)` and `Multinomial(number of trials, list of probabilities)`. The code in https://github.com/ScottishCovidResponse/Simulation.jl/pull/68#issuecomment-665158327 works for `Multinomial(number of trials, length)` but not the other one.

2020-08-12 13:15 UTC, jwscook commented
This is my current best guess, but needs checking

```julia
function median(dist::Multinomial)
         m = length(dist.p)
         v = dist.n * dist.p
         output = Int64.(floor.(v))
         @assert dist.n - m <= sum(output) <= dist.n
         p = sortperm(v .- output)
         for rp in reverse(p)
           sum(output) == dist.n && break
           output[rp] += 1
        end
        @assert sum(output) == dist.n
  return output
end
```

will put it in repo and test it when current rush is over.

2020-08-13 14:40 UTC, jwscook commented
@claireh93 Could you take a look at [this error](https://travis-ci.org/github/ScottishCovidResponse/Simulation.jl/jobs/717598326) please? I'm a bit confused by the EpiSystem constructors.

2020-08-13 14:58 UTC, jwscook commented
@claireh93 not to worry. I think I figured it out.

2020-08-13 16:36 UTC, jwscook commented
Nope, I didn't.

2020-08-14 10:38 UTC, claireh93 commented
@jwscook Sure, I'll check it out today

2020-08-14 11:11 UTC, claireh93 commented
I think the problem is that we originally had two different routes for creating the EpiSystem: One where there was a preset population (of susceptible, infected, recovered etc.) housed in `epi.spplist.human.abun` that was loaded into the system, and one where an `initial_pop` of susceptible people was fed in. Now all of these routes end up in the same function starting at line 49, which I suspect is going to cause us problems. For example, even if you reshape `initial_pop` to the right size at line 92, it causes errors in the EpiSystem tests because it sums up the entire population (infected and all) into the susceptible category. I'm not sure if this is very easy to describe by text! We can have a chat about it?

2020-08-14 18:55 UTC, jwscook commented
Sorry, wasn't able to chat today. Maybe I should start again with adding the `MedianGenerator` to that file. Which branch is best to start again from?

2020-08-17 11:19 UTC, claireh93 commented
Hi @jwscook I think `dev` should be good for this, but let me know if there are any problems

2020-08-18 19:24 UTC, richardreeve commented
@jwscook just to let you know, I've almost finished with #75, so (a) you may want to try to pull that into your branch, and (b) if you have any questions or things you want me to check, let me know...

2020-08-19 09:39 UTC, jwscook commented
This isn't ready yet because:

```julia
julia examples/Epidemiology/SEI3HRD_example.jl 
[ Info: Found data-pipeline-api v0.7.0
[ Info: Found data-pipeline-api v0.7.0
Creating Diversity to Phylo interface...
GDAL Dataset (Driver: GTiff/GeoTIFF)
File(s): 
  /home/cookj/Documents/code/Simulation.jl/src/../test/examples/ScotlandDensity2011.tif

Dataset (width x height): 700 x 750 (pixels)
Number of raster bands: 1
  [GA_ReadOnly] Band 1 (Gray): 700 x 750 (Float32)
ERROR: LoadError: BoundsError: attempt to access 8-element Array{Quantity{Float64,𝐋,Unitful.FreeUnits{(km,),𝐋,nothing}},1} at index [Bool[0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
Stacktrace:
 [1] throw_boundserror(::Array{Quantity{Float64,𝐋,Unitful.FreeUnits{(km,),𝐋,nothing}},1}, ::Tuple{Base.LogicalIndex{Int64,AxisArrays.AxisArray{Bool,1,Array{Bool,1},Tuple{AxisArrays.Axis{:row,Base.OneTo{Int64}}}}}}) at ./abstractarray.jl:541
 [2] checkbounds at ./abstractarray.jl:506 [inlined]
 [3] _getindex at ./multidimensional.jl:742 [inlined]
 [4] getindex(::Array{Quantity{Float64,𝐋,Unitful.FreeUnits{(km,),𝐋,nothing}},1}, ::AxisArrays.AxisArray{Bool,1,Array{Bool,1},Tuple{AxisArrays.Axis{:row,Base.OneTo{Int64}}}}) at ./abstractarray.jl:1060
 [5] genlookups(::GridEpiEnv{ContinuousHab{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}},NoControl,AxisArrays.AxisArray{Bool,2,Array{Bool,2},Tuple{AxisArrays.Axis{:row_idxs,UnitRange{Int64}},AxisArrays.Axis{:col_idxs,UnitRange{Int64}}}}}, ::AlwaysMovement{GaussianKernel,NoBoundary}) at /home/cookj/Documents/code/Simulation.jl/src/Epidemiology/EpiSystem.jl:269
 [6] EpiSystem(::EpiList{Simulation.EpiParams{Unitful.FreeUnits{(d^-1,),𝐓^-1,nothing}},Simulation.VirusTypes{GaussTrait{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}},Diversity.UniqueTypes},Simulation.HumanTypes{EpiMovement{AlwaysMovement{GaussianKernel,NoBoundary},Commuting},Diversity.UniqueTypes}}, ::GridEpiEnv{ContinuousHab{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}},NoControl,AxisArrays.AxisArray{Bool,2,Array{Bool,2},Tuple{AxisArrays.Axis{:row_idxs,UnitRange{Int64}},AxisArrays.Axis{:col_idxs,UnitRange{Int64}}}}}, ::Gauss{Quantity{Float64,𝚯,Unitful.FreeUnits{(K,),𝚯,nothing}}}, ::Array{Float64,2}, ::Int64; initial_infected::Int64, rngtype::Type{MedianGenerator}) at /home/cookj/Documents/code/Simulation.jl/src/Epidemiology/EpiSystem.jl:101
 [7] run_model(::Quantity{Int64,𝐓,Unitful.FreeUnits{(yr,),𝐓,nothing}}, ::Quantity{Int64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}}, ::Quantity{Int64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}}, ::Bool) at /home/cookj/Documents/code/Simulation.jl/examples/Epidemiology/SEI3HRD_example.jl:91
 [8] run_model(::Quantity{Int64,𝐓,Unitful.FreeUnits{(yr,),𝐓,nothing}}, ::Quantity{Int64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}}, ::Quantity{Int64,𝐓,Unitful.FreeUnits{(d,),𝐓,nothing}}) at /home/cookj/Documents/code/Simulation.jl/examples/Epidemiology/SEI3HRD_example.jl:19
 [9] top-level scope at /home/cookj/Documents/code/Simulation.jl/examples/Epidemiology/SEI3HRD_example.jl:112
 [10] include(::Function, ::Module, ::String) at ./Base.jl:380
 [11] include(::Module, ::String) at ./Base.jl:368
 [12] exec_options(::Base.JLOptions) at ./client.jl:296
 [13] _start() at ./client.jl:506
in expression starting at /home/cookj/Documents/code/Simulation.jl/examples/Epidemiology/SEI3HRD_example.jl:112

```

2020-08-19 11:00 UTC, claireh93 commented
Ahh I have a feeling I haven't checked that example for a while! I'll take a quick look at it and see if I can figure out where it's going wrong

2020-08-19 11:17 UTC, claireh93 commented
Okay I have pushed a tiny wee change to that file - hope that's okay!

2020-08-19 12:03 UTC, jwscook commented
Thanks @claireh93 . It ran!

2020-08-20 11:57 UTC, jwscook commented
Using the `MedianGenerator` with  `SEI3HRD_example.jl` (and making sure that the initial conditions are consistent for multi-threaded runs):
 - Two consecutive single threaded runs produce identical abundances.
 - Runs with 1, 2, 6 and 12 threads produce identical abundances.

2020-08-20 12:00 UTC, jwscook commented
@richardreeve it looks as though changes in #75 are relatively orthogonal to changes in this PR, so git should be able to merge without human intervention.

I think that this PR is complete and can be merged when the tests pass and if you're ready.

2020-08-20 12:46 UTC, richardreeve commented
@jwscook Yes, that's great. I was thinking that some of the examples would be changed, which would have had impact. I'll look at this asap.

2020-08-21 15:23 UTC, jwscook commented
Happy to merge?

2020-08-21 15:25 UTC, richardreeve commented
Just looking at the example at the moment.

2020-08-21 18:15 UTC, richardreeve requested changes
I think there was a merge problem with `EpiCache` which has reverted some changes to `dev`, and I hope I have a slightly improved suggestion for the example to make it even more deterministic... basically all looks good to go after that though if you're happy with it.

2020-08-21 18:15 UTC, richardreeve commented on examples/Epidemiology/SEI3HRD_example.jl
> +const ic_rng = Random.MersenneTwister(0) # rng for initial conditions in this file
If we make this deterministic too using the MedianGenerator we can get rid of this...
```suggestion
```

2020-08-21 18:15 UTC, richardreeve commented on examples/Epidemiology/SEI3HRD_example.jl
If we switch from `sample(...)` to `rand(rng, Multinomial(...))` then this will be deterministic in the same way as the epidemiology:
```suggestion
    w = weights(@view human(epi.abundances)[1, :])
    samp = rand(rngtype(), Multinomial(1000, w/sum(w)))
    virus(epi.abundances)[1, :] .+= 10 * samp # Virus pop in Environment
    human(epi.abundances)[2, :] .+= samp # Exposed pop
    human(epi.abundances)[1, :] .-= samp # Not susceptible
```

2020-08-21 18:15 UTC, richardreeve commented on examples/Epidemiology/SEI3HRD_example.jl
>      times = 2months; interval = 1day; timestep = 1day
We don't need 366 timesteps, and these time settings overwrite the function arguments:
```suggestion
    abuns = zeros(Int64, numclasses, N_cells, floor(Int, times / interval) + 1)
```

2020-08-21 18:15 UTC, richardreeve commented on examples/Epidemiology/SEI3HRD_example.jl
>      if do_plot
I can't make a suggestion off the bottom of your edits, but to check this is working in the example, I suggest:
```
times = 1month; interval = 10day; timestep = 1day
abuns_run1 = run_model(times, interval, timestep);
abuns_run2 = run_model(times, interval, timestep);

if stochasticmode
    abuns_run1 == abuns_run2 && @warn "Stochastic realisations are identical..."
else
    abuns_run1 == abuns_run2 || @error "Deterministic runs are different..."
end
```

2020-08-21 18:15 UTC, richardreeve commented on src/Epidemiology/EpiSystem.jl
> +  virusdecay::Array{Float64, 2}
`virusdecay` seems to have been added back in a merge error:
```suggestion
```

2020-08-21 18:15 UTC, richardreeve commented on src/Epidemiology/EpiSystem.jl
> +  nm = zeros(Float64, size(ml.matrix))
Merge error:
```suggestion
```

2020-08-21 18:15 UTC, richardreeve commented on src/Epidemiology/EpiSystem.jl
> +  return EpiSystem(ml, epilist, epienv, missing, rel, lookup, EpiCache(nm, vm, false), initial_infected)
Fix for merge problem:
```suggestion
  return EpiSystem(ml, epilist, epienv, missing, rel, lookup, EpiCache(vm, false), initial_infected)
```

2020-08-21 18:15 UTC, richardreeve commented on src/Epidemiology/EpiSystem.jl
> +    nm = zeros(Float64, size(ml.matrix))
Again, merge error:
```suggestion
```

2020-08-21 18:15 UTC, richardreeve commented on src/Epidemiology/EpiSystem.jl
> +    epi = EpiSystem(ml, epilist, epienv, missing, rel, lookup, EpiCache(nm, vm, false), initial_infected)
Again, merge error:
```suggestion
    epi = EpiSystem(ml, epilist, epienv, missing, rel, lookup, EpiCache(vm, false), initial_infected)
```

2020-08-21 18:15 UTC, richardreeve commented on src/Epidemiology/MedianGenerator.jl
> +rand(::MedianGenerator, dist::Binomial) = median(dist)
Not sure we need this:
```suggestion
```

2020-08-21 18:15 UTC, richardreeve commented on src/Simulation.jl
> +export MedianGenerator, median, rand, rand!
I'm feeling a bit fuzzy here, but do we need to re-export `median`, `rand` and `rand!`?

2020-08-21 18:19 UTC, richardreeve commented
@jwscook If you're happy with my edits (one or two have to be done by hand, but the rest should be automatic - I've never learned how to make suggestions before, I'm very excited!), then I think this is good to go - it's v cool!

2020-08-21 18:32 UTC, richardreeve commented
Closes ScottishCovidResponse/SCRCIssueTracking#681

2020-08-21 19:18 UTC, jwscook commented on src/Simulation.jl
> +export MedianGenerator, median, rand, rand!
I just commented them out and ran the tests, and they passed so I think you're right.

2020-08-21 19:19 UTC, jwscook commented on src/Simulation.jl
> +export MedianGenerator, median, rand, rand!
I just commented them out and the tests passed so you're right.

2020-08-21 19:25 UTC, jwscook commented on examples/Epidemiology/SEI3HRD_example.jl
>      if do_plot
I've made this addition in the commit I just pushed now.

2020-08-21 19:35 UTC, jwscook commented
The review functionality is great! It makes life so much easier.

On Fri, 21 Aug 2020, 19:32 Richard Reeve, <notifications@github.com> wrote:

> Closes ScottishCovidResponse/SCRCIssueTracking#681
> <https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/681>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ScottishCovidResponse/Simulation.jl/pull/68#issuecomment-678430445>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADWNA6TF5KGCV7SX5CSABFLSB24VJANCNFSM4O2L6HWA>
> .
>

2020-08-21 19:59 UTC, richardreeve commented
Yes, it is. I'd never previously worked out how to make suggestions - I'd just thought it was some superior magic that other people had!

2020-08-21 21:00 UTC, richardreeve commented on src/Epidemiology/MedianGenerator.jl
> -rand(::MedianGenerator, dist::Binomial) = median(dist)
It turns out I screwed up suggesting removing this because it's ambiguous:
```
rand(::MedianGenerator, ::Binomial): Error During Test at /home/travis/build/ScottishCovidResponse/Simulation.jl/test/test_MedianGenerator.jl:73
  Test threw exception
  Expression: rand(mg, b) == median(b)
  MethodError: rand(::MedianGenerator, ::Binomial{Float64}) is ambiguous. Candidates:
    rand(::MedianGenerator, dist::Distribution{Univariate,S}) where S<:ValueSupport in Simulation at /home/travis/build/ScottishCovidResponse/Simulation.jl/src/Epidemiology/MedianGenerator.jl:27
    rand(rng::AbstractRNG, d::Binomial) in Distributions at /home/travis/.julia/packages/Distributions/TmErr/src/univariate/discrete/binomial.jl:114
    rand(::MedianGenerator, dist) in Simulation at /home/travis/build/ScottishCovidResponse/Simulation.jl/src/Epidemiology/MedianGenerator.jl:25
  Possible fix, define
    rand(::MedianGenerator, ::Binomial)
```
So this needs to go back in: 
```
  rand(::MedianGenerator, dist::Binomial) = median(dist)
```

2020-08-23 11:59 UTC, richardreeve approved these changes

2020-08-23 12:01 UTC, merged

2020-08-24 07:55 UTC, jwscook commented
[Party parrot](https://ppaas.herokuapp.com/partyparrot?overlay=&overlayWidth=20&overlayHeight=40&overlayOffsetX=0&overlayOffsetY=0) :tada:

2020-08-24 15:04 UTC, richardreeve commented
Yes, fantastic! I think we can slowly start working out how to do lots of the basic testing using this now...