Example use of data pipeline for reading parameters
ScottishCovidResponse/Simulation.jl pull request #72
Opened 2020-07-24 17:12 UTC by sdl1

- Updates dependency on `SimulationData` to 0.4.0
- Adds an example data pipeline config file (`data_config.yaml`)
- Changes the `Scotland_run` example to read a parameter out of this file

To actually get this to work one needs to download the data repository. We cannot easily do this with the SimulationData package, until [this issue](https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/695) is fixed. So instead you can do something like the following:
```bash
git clone https://github.com/ScottishCovidResponse/data_pipeline_api.git
cd data_pipeline_api
# Install all the requirements, here by just installing the package through pip.
# Or could use conda instead
virtualenv -p python3 venv
source venv/bin/activate
pip install data_pipeline_api
# Run the download script with our config file
# Note: this runs the one in the working directory, not the one installed through pip
python -m data_pipeline_api.registry.download --config ../data_config.yaml 
```

2020-07-24 21:26 UTC, richardreeve commented
It looks good to me, and the tests pass, but it doesn't work on my computer. @sdl1 Do you have any thoughts about why there isn't a `metadata.yaml` file created for me?
```
bleaberry[~/Documents/git/julia/Simulation] julia examples/Epidemiology/Scotland_run.jl 
Creating Diversity to Phylo interface...
[ Info: Found data-pipeline-api v0.5.0
could not find metadata.yaml
ERROR: LoadError: PyError ($(Expr(:escape, :(ccall(#= /Users/richardr/.julia/packages/PyCall/zqDXB/src/pyeval.jl:38 =# @pysym(:PyEval_EvalCode), PyPtr, (PyPtr, PyPtr, PyPtr), o, globals, locals))))) <class 'KeyError'>
KeyError("could not find filename in {'data_product': 'human/infection/SARS-CoV-2/asymptomatic-period', 'component': 'asymptomatic-period'}")
  File "/Users/richardr/.julia/packages/PyCall/zqDXB/src/pyeval.jl", line 1, in <module>
    const Py_single_input = 256  # from Python.h
  File "/Users/richardr/.julia/conda/3/lib/python3.7/site-packages/data_pipeline_api/standard_api.py", line 112, in read_estimate
    with self.open_parameter_file_for_read(data_product, component) as file:
  File "/Users/richardr/.julia/conda/3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/richardr/.julia/conda/3/lib/python3.7/site-packages/data_pipeline_api/standard_api.py", line 81, in open_parameter_file_for_read
    self.file_api.open_for_read(data_product=data_product, component=component)
  File "/Users/richardr/.julia/conda/3/lib/python3.7/site-packages/data_pipeline_api/file_api.py", line 190, in open_for_read
    raise KeyError(f"could not find {MetadataKey.filename} in {read_metadata}")
...
```

2020-07-25 14:18 UTC, sdl1 commented
Hi @richardreeve , did you do the registry download step first? That should create a folder `data` with everything in it including `metadata.yaml`. If it doesn't then something is going wrong somewhere.

2020-07-25 17:28 UTC, richardreeve commented
Thanks @sdl1. I'm a complete idiot 🤦! I read through the code, tested it and assumed it was all working without reading the comment above. Okay, this is great!

2020-07-25 17:30 UTC, richardreeve requested changes
Can you move the `data_config.yaml` into the example folder with `Scotland_run.jl`, and then add instructions (basically what's in the comment) somewhere to say how to run that example now (presumably involving a bit of fiddling with the paths)?

2020-07-25 17:30 UTC, richardreeve commented on data_config.yaml
> +data_directory: data
Can we move this file from the root into the examples/Epidemiology folder alongside Scotland_run.jl?

2020-07-25 17:47 UTC, richardreeve commented
I know I have just said this is basically good-to-go, and it is, but if there's any chance of outputting the Scotland_run.jl run output as a data product here, then we would have a read-and-write use of the data pipeline, which would be even better!

2020-07-27 09:54 UTC, sdl1 commented
Yes I'll try outputting the data as well so we have a complete read-write example in this PR.

I think we should leave loading in `human/demographics/population/scotland` for a separate PR since I have a feeling it will need some more involved changes to wrangle stuff into the right format.

2020-07-27 12:00 UTC, sdl1 commented on data_config.yaml
> +data_directory: data
Moved this file, and added a new page to `docs` describing basic usage of the pipeline.

2020-07-27 17:23 UTC, sdl1 commented
I've added a `write_array` command to write out the final abundances matrix. (It seems like the data_pipeline_api doesn't support progressive writes to a single component so this is probably the easiest thing to do right now.)

2020-07-27 19:59 UTC, AlexRobson commented
May want to get https://github.com/ScottishCovidResponse/SimulationData.jl/pull/19 in and then update the version as appropriate so it picks up those changes.

2020-07-28 14:20 UTC, AlexRobson commented on Manifest.toml
> +repo-rev = "v0.4.0"
0.4.1

2020-07-28 14:31 UTC, AlexRobson commented on docs/src/data.md
> +# Install all the requirements, here by creating a virtualenv and installing the package
Is this workaround needed in 0.7.0?

2020-07-28 14:34 UTC, sdl1 commented on docs/src/data.md
> +# Install all the requirements, here by creating a virtualenv and installing the package
I don't think so, but we would need to add a `download` function to the SimulationData wrapper (this issue: https://github.com/ScottishCovidResponse/SimulationData.jl/issues/13)

2020-07-28 16:33 UTC, sdl1 commented on Manifest.toml
> +repo-rev = "v0.4.0"
Updated

2020-07-28 22:45 UTC, richardreeve commented on docs/src/data.md
> +git clone -b d2efc99 https://github.com/ScottishCovidResponse/data_pipeline_api.git
This doesn't seem to work to clone a specific commit, but I can't find out how to do that. Do you need to clone and then check out the commit?

2020-07-28 22:45 UTC, richardreeve commented on docs/src/data.md
> +python -m data_pipeline_api.registry.download --config <path_to_config_file>
Running this seems to error out while downloading lots of files that haven't been requested in the config.yaml file. Does that happen for you too? I was only expecting it to download the files specifically mentioned in the yaml file...

2020-07-28 22:46 UTC, richardreeve commented on docs/src/data.md
> +# Install all the requirements, here by creating a virtualenv and installing the package
Obviously the simpler the better...

2020-07-29 09:05 UTC, sdl1 commented on docs/src/data.md
> +git clone -b d2efc99 https://github.com/ScottishCovidResponse/data_pipeline_api.git
Sorry I thought I tested that command but you're right it doesn't work. Yes you can do
```
git clone https://github.com/ScottishCovidResponse/data_pipeline_api.git
cd data_pipeline_api
git checkout d2efc99 
```

2020-07-29 09:10 UTC, sdl1 commented on docs/src/data.md
> +# Install all the requirements, here by creating a virtualenv and installing the package
Yeah, I'm wondering if we should wait for 0.7.0 to be released before merging this PR, it will make things a lot simpler.

2020-07-29 09:10 UTC, sdl1 commented on docs/src/data.md
> +python -m data_pipeline_api.registry.download --config <path_to_config_file>
Yes this was happening on `data_pipeline_api#master` for me, hence fixing to that specific commit for now, where it should only download the specified data, until we can work out why...

2020-07-29 12:16 UTC, sdl1 commented
Plan is:
1. Wait for `data_pipeline_api` v0.7.0 to be released
2. Update `SimulationData.jl` to use `0.7.0` and close out all the issues there, including wrapping the registry download step
3. Update this PR with the new version of `SImulationData.jl`

2020-07-29 14:03 UTC, sdl1 commented on docs/src/data.md
> +python -m data_pipeline_api.registry.download --config <path_to_config_file>
Ok this is fixed on `data_pipeline_api#master` for me now, maybe try that?

2020-07-30 10:27 UTC, richardreeve commented
@sdl1 I see that data_pipeline_api v0.7.0 was just released btw...

2020-07-30 10:27 UTC, richardreeve commented on docs/src/data.md
> +python -m data_pipeline_api.registry.download --config <path_to_config_file>
Yes, is fixed for me too

2020-07-30 15:23 UTC, sdl1 commented
> @sdl1 I see that data_pipeline_api v0.7.0 was just released btw...

Yep, I've just checked and it should work to have a wrapper in SimulationData for the registry download. So the download step will get much easier.

2020-07-31 13:13 UTC, richardreeve commented
Cool. That's v good news.

2020-07-31 17:29 UTC, sdl1 commented
@richardreeve this should be ready now I think. There is now a download wrapper so that step should be easy (🤞 ), I've updated the PR description on how to use that.

2020-08-12 02:35 UTC, richardreeve commented
Thanks @sdl1, @AlexRobson - I added in running the download wrapper into the `Scotland_run.jl` example and updated some project and manifest toml files so they still work (e.g. the docs). The only thing that still doesn't work is the windows code in Appveyor - it seems to not be able to find pip during the python installation. If you happen to have any thoughts about how to fix it, it would be great, but I'm going to merge this PR anyway...

2020-08-12 02:36 UTC, richardreeve approved these changes

2020-08-12 02:49 UTC, merged