DataRegistryUtils
ScottishCovidResponse/Simulation.jl pull request #84
Opened 2021-01-29 15:45 UTC by claireh93

Implement DataRegistry utils in `Scotland_run.jl` and remove SimulationData. Use sql to aggregate the Scottish population array by age category.

2021-03-01 17:41 UTC, richardreeve requested changes
I obviously haven't looked at the new DataRegistry interface yet, but this looks more complex than I was hoping I have to admit. Anyway, something for when we have time to get together?

2021-03-01 17:41 UTC, richardreeve commented on .gitignore
> +access*
That seems like a dangerous pattern for .gitignore

2021-03-01 17:41 UTC, richardreeve commented on .gitignore
> +**/*.txt
These seem like dangerous patterns for .gitignore too

2021-03-01 17:41 UTC, richardreeve commented on .gitignore
> +
Generally, I'm not sure what's going on here. Do we need to fill the repo with all of these files and then ignore them? The whole thing makes me a bit nervous...

2021-03-01 17:41 UTC, richardreeve commented on Project.toml
> +HDF5 = "^0.15.0"
Won't we need compat limits on everything? Should you add a CompatHelper github action that watches dev (a la Phylo.jl) to fix the rest?

2021-03-01 17:41 UTC, richardreeve commented on examples/Epidemiology/data_config.yaml
> -      data_product: human/infection/SARS-CoV-2/*
Does * not work any longer?

2021-03-01 17:41 UTC, richardreeve commented on test/simulationdata/test_integration.jl
> +# using SimulationData
I guess you just delete this file?

2021-03-01 17:41 UTC, richardreeve commented on src/Epidemiology/EpiHelper.jl
>      h5open(h5fn, "w") do fid
I'm not sure what's going on here... don't we have write working yet in the pipeline? I thought that was now fixed?

2021-03-03 16:28 UTC, claireh93 commented on src/Epidemiology/EpiHelper.jl
>      h5open(h5fn, "w") do fid
I don't think so yet, but at any rate, we can merge this in on a subsequent PR.

2021-04-26 09:41 UTC, closed without merging